language: java
jdk: openjdk11
sudo: true

before_install:
  - chmod +x mvnw
  - wget  http://arx.deidentifier.org/wp-content/uploads/downloads/libarx-3.7.1.jar -P ./src/main/resources/

script:
  mvn test
