language: java
jdk: openjdk11
dist: trusty
sudo: true

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - CC_TEST_REPORTER_ID=$cc_token

before_install:
  - chmod +x mvnw
  - wget  https://github.com/oslomet-arx-as-a-service/arx-dependency/raw/master/libarx-3.7.1.jar -P ./src/main/resources/
  - openssl aes-256-cbc -K $encrypted_545802352a58_key -iv $encrypted_545802352a58_iv -in google_cloud_api_key.json.enc -out google_cloud_api_key.json -d
install:
  - mvn -q install:install-file -Dfile=src/main/resources/libarx-3.7.1.jar -DgroupId=org.deidentifier -DartifactId=libarx -Dversion=3.7.1 -Dpackaging=jar

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn clean install -B -q

after_script:
 - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage -d ./target/site/jacoco/jacoco.xml --input-type jacoco
 - ./cc-test-reporter upload-coverage -d

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      tags: true
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: target/generated-docs
    github_token: $GITHUB_DOCS_TOKEN
    keep_history: true
    on:
      tags: true
      branch: master
