apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arxaastesting
  namespace: default
  labels:
    team: {{team}}
spec:
  image: arxaas/arxaas:{{version}}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /isAlive
    timeout: 1
    initialDelay: 60
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /nais/isReady
    timeout: 1
    initialDelay: 60
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /prometheus
  istio:
    enabled: false
  resources:
    limits:
      cpu: 1500m
      memory: 4800Mi
    requests:
      cpu: 200m
      memory: 512Mi
